name: update-runtime

on:
  repository_dispatch:
    types: debug-updater
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * 0"

# Checks out HEAD from upstream/repo
# Pushes to fork/repo
# Opens PR against upstream
# Requires a secret in this repo named PAT with access to fork

jobs:
  check:
    strategy:
      matrix:
        config:
          - repo: "de.klayout.KLayout"
            manifest: "de.klayout.KLayout.yaml"
            upstream: flathub
            fork: wshanks

    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        repository: ${{ matrix.config.upstream }}/${{ matrix.config.repo }}
        path: ${{ matrix.config.repo }}
        persist-credentials: false

    - name: Checkout updater
      uses: actions/checkout@v2
      with:
        path: update_runtime

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ${GITHUB_WORKSPACE}/update_runtime/requirements.txt

    - name: Install dependencies - flatpak
      run: |
        sudo apt update
        sudo apt install flatpak

    - name: Install Flathub
      run: |
        sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
        sudo flatpak update --appstream

    - name: Run update_runtime.py
      run: python ${GITHUB_WORKSPACE}/update_runtime/update_runtime.py ${GITHUB_WORKSPACE}/${{ matrix.config.repo }}/${{ matrix.config.manifest }}

    - name: Show diff
      run: git diff
      working-directory: ${{ matrix.config.repo }}

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        path: ${{ matrix.config.repo }}
        title: Update runtime version
        token: ${{ secrets.PAT }}
        push-to-fork: ${{ matrix.config.fork }}/${{ matrix.config.repo }}
